apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
        - name: nginx
          image: sovichea10/nginx:v1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: 500m
          ports:
            - containerPort: 80
          env:
            # Inject the FPM Host as we did with Docker Compose
            - name: laravel-app-host
              value: laravel-in-kubernetes:9000
      hostNetwork: true
      dnsPolicy: Default
      