---
kind: Namespace
apiVersion: v1
metadata:
  name: nginx

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources: {}
          ports:
            - containerPort: 80
      hostNetwork: false
      dnsPolicy: Default
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  # sessionAffinity: None
  # externalTrafficPolicy: Cluster
  # ipFamilies:
  #   - IPv4
  # ipFamilyPolicy: SingleStack
  # internalTrafficPolicy: Cluster
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30001
