apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
      app: nginx 
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      # Expose node port must be in range 30000-32000
      NodePort: 30000