apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-sovichea
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/alias-name: deployment
    kubesphere.io/creator: sovichea
    kubesphere.io/description: deployment
    kubesphere.io/relatedHPA: nginx
spec:
  selector:
      app: nginx 
  type: LoadBalancer
  # type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32100  # Expose node port must be in range 30000-32767