apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: laravel
data:
  laravel-app.conf: |
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;
    server {
      listen 81;

      root /var/www/laravel10/public;
      index index.php index.html;

      limit_req zone=mylimit burst=20;
      location / {
          try_files $uri $uri/ /index.php?$query_string;
          gzip_static on;
      }

      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass app:9000;
          fastcgi_index index.php;
          fastcgi_buffers 8 1600k;
          fastcgi_buffer_size 3200k;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }
      # Log files for debug
      error_log  /var/log/nginx/laravel10-error.log;
      access_log /var/log/nginx/laravel10-access.log;
    }