apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: 500m
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-data
      emptyDir: {}
  hostNetwork: true
  dnsPolicy: Default
  restartPolicy: Always