# ConfigMap Database
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  DB_CONNECTION: mysql
  DB_HOST: myapp-mysql 
  DB_PORT: '3306'
  DB_DATABASE: laravel 
  DB_USERNAME: root 
  DB_PASSWORD: secret
