kind: Deployment
apiVersion: apps/v1
metadata:
  name: laravel10
  namespace: laravel10
  labels:
    app: laravel10
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubesphere.io/alias-name: api
    kubesphere.io/creator: sovichea
    kubesphere.io/description: api
    kubesphere.io/relatedHPA: laravel10
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laravel10
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laravel10
      annotations:
        kubesphere.io/creator: sovichea
        kubesphere.io/imagepullsecrets: '{}'
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: time-zone
          hostPath:
            path: /etc/timezone
            type: ''
        - name: hosts
          hostPath:
            path: /etc/hosts
            type: ''
      containers:
        - name: laravel-10
          # image: 'registry.mpwt.gov.kh:4000/sovichea/laravel10-testing_api:v2'
          image:  $URL/calendar-api:$TAG
          ports:
            - name: http-9000
              containerPort: 9000
              protocol: TCP
            - name: http-81
              containerPort: 81
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: time-zone
              mountPath: /etc/timezone
            - name: hosts
              mountPath: /etc/hosts
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: private-registry
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
