apiVersion: v1
kind: Service
metadata:
  name: laravel-in-kubernetes
spec:
  selector:
    app: laravel-in-kubernetes
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32000 # Port of cluster node to access the service