kind: Secret
apiVersion: v1
metadata:
  name: private-registry
  namespace: laravel10
  annotations:
    kubesphere.io/alias-name: docker-image
    kubesphere.io/creator: sovichea
    kubesphere.io/description: 'docker-image '
    secret.kubesphere.io/force-insecure: 'true'
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwOi8vcmVnaXN0cnkubXB3dC5nb3Yua2g6NDAwMCI6eyJ1c2VybmFtZSI6InNvdmljaGVhIiwicGFzc3dvcmQiOiJ4eXpSZWdpczIwMjNAeSIsImVtYWlsIjoiIiwiYXV0aCI6ImMyOTJhV05vWldFNmVIbDZVbVZuYVhNeU1ESXpRSGs9In19fQ==
type: kubernetes.io/dockerconfigjson
