---
- name: Kubernetes-master
  hosts: kubernetes-master
  become: true
  tasks:
    - name: Initialize the kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10" --node-name k8-master --pod-network-cidr=192.168.0.0/16

    - name: Setup kubeconfig for user
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/.kube
        - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - sudo chown $(id -u):$(id -g) $HOME/.kube/config
    
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: 
        copy content: "{{ join_command.stdout_lines[0] }}" 
        dest: "./join-command" 